### ISSUE TITLE
Unable to set samba password

### ISSUE THREAD

**Issue by panny-P** [fusiondirectory/fusiondirectory-plugins#12]
I've added samba setting for ldap user, but I can't find the setting for samba password on samba tab.

**Comment by bilbo-the-hobbit** [comment]
Hello,

there is none its managed by the main password function.

You have two case 

- installing the samba plugin at the same time as other plugin, samba hash will be created at the same time as the unix password

- Installing the samba plugin after user have been created and have a password set. You need to change password to make FusionDirectory set the samba hash, as we don't know the password and so cannot put the samba hash. 

Cheers

**Comment by panny-P** [comment]
Thanks a lot bilbo-the-hobbit! You save my life. :+1:
