### ISSUE TITLE
"Fatal error: not all POST variables have been transferred by PHP - please inform your administrator!

### ISSUE THREAD

**Issue by feth** [fusiondirectory/fusiondirectory-plugins#2]
What I do:

I have a quite big DNS zone (300 entries). Whenever I add an alias, for instance, I get 
"Fatal error: not all POST variables have been transferred by PHP - please inform your administrator!"

I expanded the POST size from 8 to 20 M in php.ini

It works fine on my smaller zones.

Version: 
© 2002-2014 The FusionDirectory team, 1.0.6

**Comment by bilbo-the-hobbit** [comment]
Hello,

sorry for the very late answer did you test with the recent version of FusionDirectory 1.0.9.1, to see if you reproduce it.

By the way DNS and DHCP are in the progress of been completelty rewritten in 1.1

Cheerq

**Comment by bilbo-the-hobbit** [comment]
hello,

no answer to this ? i'am closing it

cheers
