### ISSUE TITLE
Prevent admin from changing passwords

### ISSUE THREAD

**Issue by Victor-Morel** [fusiondirectory/fusiondirectory-plugins#21]
Hello,
I'm using fusiondirectory with the ppolicy plugin, and I was wondering if it's possible to prevent the admin from changing passwords of other users.  
I would like only to rely on the recovery method.
Thanks

**Comment by MCMic** [comment]
I think you need to redo the admin acl role to give rights on everything but passwords.

**Comment by Victor-Morel** [comment]
Ok, thanks for your answer.
I presume this is reversible? i.e. I'd like the admin account never to have access to password change again, so not as to be accountable if there is a legal procedure related to a user: can FD enable it?

**Comment by MCMic** [comment]
I’m not sure I understand your need. 
Everything you configure can always be reconfigured an other way. You may remove the admin the right to change the ACLs, but that means you won’t ever be able to change ACLs again. I think at this point you should keep an admin account and use another role with less rights for this.

**Comment by Victor-Morel** [comment]
I'd like the admin account not to be able to change passwords of users ever again.
Your solution is interesting, but I was wondering if it's possible to use a **stronger** method: _i.e._, use cryptographic techniques.
For instance, requiring a key for changing the password, and that key would be only owned by the user.
I understand if it sounds out of scope.

**Comment by MCMic** [comment]
Yes, this is out of scope.

There will always be an admin able to change the password, whether at the LDAP level or the server level.
Cryptography can hide the password from the admin but it does not prevent changing it.
You should not give an admin account to anyone which is not allowed to change passwords. Use an ACL role with less rights.

**Comment by Victor-Morel** [comment]
No of course I won't give anyone an admin account.
I wanted to _release_ any burden of liability on the admin, the password being able to decrypt users' data.
We'll try something similar to the approach proposed by [Schneier](https://www.schneier.com/blog/archives/2009/07/laptop_security.html) to achieve our goal.
Thanks for your help!

**Comment by bilbo-the-hobbit** [comment]
@Victor-Morel,

hello if you achieve something or want to discuss more feel free to ping me here

Cheers
