### ISSUE TITLE
Link "to get help" in README.md just leads to a 404

### ISSUE THREAD

**Issue by gohrner** [fusiondirectory/fusiondirectory-plugins#22]
The link "to get help" in the README.md file (displayed as the description page below the GIT listing) just leads to a 404 error. Probably the target web site was restructured.

**Comment by bilbo-the-hobbit** [comment]
hello @gohrner,

yes the website is currently being redesigned completely, should be ok start of september :)

in the mean time https://fusiondirectory-user-manual.readthedocs.io/en/1.3/contact/contact.html

can be used

Cheers

**Comment by bilbo-the-hobbit** [comment]
hello @gohrner,

fix have been done they will appears in the next sync of our code from gitlab

Cheers
