### ISSUE TITLE
LDAP-Plugin: Adding a host under systems and under a specific subnet breaks

### ISSUE THREAD

**Issue by grharry** [fusiondirectory/fusiondirectory-plugins#24]
Adding a host under systems and under a specific subnet breaks with 

PHP Fatal error:  Uncaught TypeError: Argument 4 passed to DhcpHostsAttribute::postLdapSave() must be of the type array, string given, called in 
/usr/share/fusiondirectory/plugins/admin/systems/class_dhcpSystem.inc on line 405 and defined in /usr/share/fusiondirectory/plugins/admin/systems/class_dhcpSystem.inc:159\nStack trace:\n#0 /usr/share/fusiondirectory/plugins/admin/systems/class_dhcpSystem.inc(405): DhcpHostsAttribute->postLdapSave(Object(ldapMultiplexer), false, false, '10.168.1.20', '10.168.1.20', false, '00:02:d1:08:05:...', '00:02:d1:08:05:...')\n#1 /usr/share/fusiondirectory/include/simpleplugin/class_simplePlugin.inc(1226): dhcpSystem->ldap_save()\n#2 /usr/share/fusiondirectory/include/simpleplugin/class_simpleTabs.inc(430): simplePlugin->save()\n#3 /usr/share/fusiondirectory/include/simpleplugin/class_simpleManagement.inc(828): simpleTabs->save()\n#4 /usr/share/fusiondirectory/include/simpleplugin/class_simpleManagement.inc(945): simpleManagement->applyChanges('apply', Array, Array)\n#5 /usr/share/fusiondirectory/includ in /usr/share/fusiondirectory/plugins/admin/systems/class_dhcpSystem.inc on line 159, referer: http://10.0.173.187/main.php?plug=81

**Comment by bilbo-the-hobbit** [comment]
hello @grharry,

* can you tell us which version of FusionDirectory
* Which version of PHP
* Wich Linux Distribution

Thanks

**Comment by grharry** [comment]
F.D. version = 1.3-1 
PHP version = 7.3  
Debian Buster 

This happens when a network device is added in systems. 
The network Device form has single entries for mac address and ip address while all other devices can take multiple entries on both. 
Thus the error DhcpHostsAttribute::postLdapSave() must be of the type array, string given, called in

Regards, 
Harry

**Comment by grharry** [comment]
> hello @grharry,
> 
> * can you tell us which version of FusionDirectory
> * Which version of PHP
> * Wich Linux Distribution
> 
> Thanks

F.D. version = 1.3-1
PHP version = 7.3
Debian Buster

This happens when a network device is added in systems.
The network Device form has single entries for mac address and ip address while all other devices can take multiple entries on both.
Thus the error DhcpHostsAttribute::postLdapSave() must be of the type array, string given, called in

Regards,
Harry

**Comment by MCMic** [comment]
See https://gitlab.fusiondirectory.org/fusiondirectory/fd-plugins/-/issues/6063

**Comment by bilbo-the-hobbit** [comment]
hello @grharry,

will be inside 1.3.1 due soon

Cheers
