### ISSUE TITLE
Unclear where to report bugs

### ISSUE THREAD

**Issue by NightTsarina** [fusiondirectory/fusiondirectory-plugins#26]
Hi,

The main FD page seems to indicate that bug reports should be posted here, but then I see that most reports are in gitlab, and that the only report open here did not get any attention for weeks.

Then, I can't register in gitlab to open a bug report. One of dozens of broken links I have found today: https://register.fusiondirectory.org/

To make things worse, it seems that there is a third bug tracker (redmine), but I can't find its location anywhere.

**Comment by MCMic** [comment]
Bugs should go to https://gitlab.fusiondirectory.org
As stated on https://gitlab.fusiondirectory.org you need to create an account on https://register.fusiondirectory.org

What is broken on https://register.fusiondirectory.org ? Please report the exact problem you encounter.

The redmine instance is what we used before gitlab, years ago, and migrated from. It does not exists anymore.

**Comment by NightTsarina** [comment]
The day I reported this bug I got an empty page when trying to register.

**Comment by NightTsarina** [comment]
If bugs should go to gitlab, could you put a notice here, and close the tracker?
