### ISSUE TITLE
Many problems with mail plugins

### ISSUE THREAD

**Issue by NightTsarina** [fusiondirectory/fusiondirectory-plugins#27]
Hi,

A customer of mine has a postfix + spamassassin + dovecot + pigeonhole system using a custom LDAP schema and scripts to manage it. I am in the process of evaluating FD to see if this would solve some of our admin problems, but this is proving very challenging.

This is all using packages from Debian buster (stable), except for FusionDirectory, for which I am using the Debian bullseye (testing) packages.

After days of reading documentation and code, I still can't understand the relationship between the various mail plugins, what exact functionality each one gives, and how to make FD work as I want. This is not a great report, because I am not even sure what the bug(s) are. It is about lack of documentation, implementation problems, and missing functionality. I am close to discarding the idea of using FD completely, and going back to manual LDAP administration.

Some of the problems I have encountered:

* In the services configuration, it is never clear what hostname is used for connections: the system hostname, one of its IP addresses, or the hostname defined in the service itself.
  * It is also not evident why it is mandatory to define IP addresses, when I have DNS for that.
* In the user mail settings, if there are two or more mail services (generic, dovecot or cyrus) within the same **server**, they all show as a single entry. I can't choose which actual service to use.
  * It is also not clear why does FD need to connect to the service at that point, which is giving me failures all the time as I try to debug this.
* It seems that at some point there was some decent sieve support, and it is still announced in FD description. But after many attempts, it seems it is only used by the cyrus plugin, and only to set a vacation message, without allowing the user to customise the script. Is there any other way? Can I use sieve with dovecot?
* I still do not understand what is the advantage of configuring a dovecot service over a generic imap service. What does the plugin do? The documentation for most plugins is nonexistant.
* I have not found any authoritative documentation of how to link postfix and dovecot to FD. So far I had to guess from the PHP code, but that is not easy to follow either.
* I still don't fully understand what the  "Account identification attribute"  and "Mail user template"  settings are for. I have only seen them used to **connect** to the IMAP server, but the documentation and contextual help seem to indicate that they are used for account creation.

I am looking for answers to these questions, but more importantly, I think these should all be documented and the weird behaviours fixed.

**Comment by MCMic** [comment]
> * In the services configuration, it is never clear what hostname is used for connections: the system hostname, one of its IP addresses, or the hostname defined in the service itself.

The hostname defined in the service itself.

>   * It is also not evident why it is mandatory to define IP addresses, when I have DNS for that.

In the upcoming 1.4 this is configurable.

> * In the user mail settings, if there are two or more mail services (generic, dovecot or cyrus) within the same **server**, they all show as a single entry. I can't choose which actual service to use.

Hum, do these services share the same email domain?

>   * It is also not clear why does FD need to connect to the service at that point, which is giving me failures all the time as I try to debug this.

To check if the mailbox exist, to create it if needed, to get/set the quota, and other options depending on mail methods.

> * It seems that at some point there was some decent sieve support, and it is still announced in FD description. But after many attempts, it seems it is only used by the cyrus plugin, and only to set a vacation message, without allowing the user to customise the script. Is there any other way? Can I use sieve with dovecot?

Sieve is only used in the cyrus plugin to apply some settings like vacation message.
Dovecot plugin does not make use of sieve as far as I remember.

> * I still do not understand what is the advantage of configuring a dovecot service over a generic imap service. What does the plugin do? The documentation for most plugins is nonexistant.

It adds quota support, mainly. Dovecot has a good LDAP support so not much specific code is needed.
The plugin may support more things in the future, we did not have many contributions on dovecot plugin for now.

> * I have not found any authoritative documentation of how to link postfix and dovecot to FD. So far I had to guess from the PHP code, but that is not easy to follow either.

Official documentation is at https://fusiondirectory-user-manual.readthedocs.io/en/latest/plugins/dovecot/index.html but it’s quite short. Contributions are welcome.
You may also look at dovecot documentation regarding LDAP support.

> * I still don't fully understand what the  "Account identification attribute"  and "Mail user template"  settings are for. I have only seen them used to **connect** to the IMAP server, but the documentation and contextual help seem to indicate that they are used for account creation.

Hum, in dovecot case account creation is handled on server side so they may only be used for connection.
