### ISSUE TITLE
Add GitHub as social handler in 'Personal' plugin

### ISSUE THREAD

**Issue by schmittner** [fusiondirectory/fusiondirectory-plugins#29]
It would be nice to be able to add a GitHub identity. Adding the following class to `personal/personal/personal/class_socialHandlers.inc` should do the trick:

```php
class socialHandler_github extends socialHandler
{
  static function getName ()
  {
    return _('GitHub');
  }

  protected $baseurl = 'https://github.com';
}
```

**Comment by bilbo-the-hobbit** [comment]
hello @schmittner,

interesting indeed, what is the format of the github identity, could you give us and exemple ?

Cheers

**Comment by schmittner** [comment]
According to the rules that are displayed when creating a new account:

- may only contain alphanumeric characters or hyphens
- cannot have multiple consecutive hyphens
- cannot begin or end with a hyphen
- maximum 39 characters

Somebody already made a regex for this: https://github.com/shinnn/github-username-regex

**Comment by bilbo-the-hobbit** [comment]
> According to the rules that are displayed when creating a new account:
> 
>     * may only contain alphanumeric characters or hyphens
> 
>     * cannot have multiple consecutive hyphens
> 
>     * cannot begin or end with a hyphen
> 
>     * maximum 39 characters
> 
> 
> Somebody already made a regex for this: https://github.com/shinnn/github-username-regex

thanks we will be looking into it

Cheers

**Comment by bilbo-the-hobbit** [comment]
hello @schmittner,

has been merged to https://gitlab.fusiondirectory.org/fusiondirectory/fd-plugins/-/issues/6085

pending codestyle review
