### ISSUE TITLE
Add Google Scholar as social handler in 'Personal' plugin

### ISSUE THREAD

**Issue by schmittner** [fusiondirectory/fusiondirectory-plugins#30]
Along the lines of #29, it would be nice to be able to add a [Google Scholar](https://scholar.google.com/citations?user=CUO0vDcAAAAJ) author identity, which many researchers have. Since you already offer ORCID, I assume that this would be interesting as well.

According to [Wikidata](https://www.wikidata.org/wiki/Property:P1960):

* Base URL is `https://scholar.google.com/citations?user=AUTHOR_ID`
* Regex for the `AUTHOR_ID` is `[-_0-9A-Za-z]{12}`

Thanks for your great work.

**Comment by bilbo-the-hobbit** [comment]
hello @schmittner,

has been merged to https://gitlab.fusiondirectory.org/fusiondirectory/fd-plugins/-/issues/6085

pending codestyle review
