### ISSUE TITLE
Dashboard broken with ppolicy plugin

### ISSUE THREAD

**Issue by sideeffect42** [fusiondirectory/fusiondirectory-plugins#34]
**Describe the bug**

Cannot open the dashboard on a FusionDirectory (version 1.3) installation with the ppolicy plugin installed:

```
Fatal error:  Uncaught FusionDirectoryException: Could not find ACL for attribute "mail" in /usr/share/fusiondirectory/include/class_objects.inc:89
Stack trace:
#0 /usr/share/fusiondirectory/plugins/addons/dashboard/class_dashBoardPPolicy.inc(113): objects::ls()
#1 /usr/share/fusiondirectory/plugins/addons/dashboard/class_dashBoardPPolicy.inc(70): dashboardPpolicy->compute_accounts_info()
#2 /usr/share/fusiondirectory/include/simpleplugin/class_simpleTabs.inc(92): dashboardPpolicy->__construct()
#3 /usr/share/fusiondirectory/plugins/addons/dashboard/tabs_dashBoard.inc(25): simpleTabs->__construct()
#4 /usr/share/fusiondirectory/include/class_objects.inc(279): tabs_dashboard->__construct()
#5 /usr/share/fusiondirectory/include/simpleplugin/class_simplePlugin.inc(2054): objects::open()
#6 /usr/share/fusiondirectory/plugins/addons/dashboard/main.inc(21): simplePlugin::mainInc()
#7 /usr/share/fusiondirectory/html/main.php(284): require('/usr/share/fusi...')
#8 {main}
thrown in /usr/share/fusiondirectory/include/class_objects.inc on line 89
```

**To Reproduce**

1. install FusionDirectory,
2. install the ppolicy plugin,
3. log in to the web interface,
5. open the dashboard from the reporting section of the web interface,
6. see error.

**Expected behavior**

The dashboard is shown.

**Server**

 - OS: Devuan GNU/Linux
 - PHP: PHP 7.4.28
 - PHP provenance: original Devuan

**Plugin with the defect

 - Plugin: ppolicy

**Additional context**

Workarounds:
1. Install the FusionDirectory mail plugin;
2. Comment out this line: https://github.com/fusiondirectory/fusiondirectory-plugins/blob/d62a0308f8dc4980a1909ac73b42d5e870225c4d/ppolicy/addons/dashboard/class_dashBoardPPolicy.inc#L107

**Comment by bilbo-the-hobbit** [comment]
hello @sideeffect42 

it's corrected in the future 1.3.1

Cheers
