### ISSUE TITLE
Invitations misshandle base

### ISSUE THREAD

**Issue by Window-Hero** [fusiondirectory/fusiondirectory-plugins#36]
**Describe the bug**
When a public form with a non-root creation base is used by an invitation that isn't stored on root, the two bases are combined resulting in an (usually) invalid root, causing the form to error.  If base is left as an altered field in the public form, it is either similarly not handled correctly, or is ignored entirely, I was not able to verify which in my troubleshooting.  It does seem that if you leave the invitation at root, but set a non-root value for the creation base for the public form, it will initially create the user and their registration at the creation base defined in the public form, but then move it to root when you confirm the user.

**To Reproduce**
1. Create a public form with a creation base other than root
2. Create an invitation that uses that public form and store it somewhere other than root
3. Send that invitation to yourself and fill in the form
4. Assuming the resultant mess of combined base doesn't exist in your directory, the form will fail 

**Expected behavior**
My initial assumption was that the registration and user would be created at the creation base defined in the public form, and would then be moved to the base of the invitation after the registration was confirmed.  Failing that, I would expect one or the other value to be respected, and I would expect a value set by an altered field in the public form to overwrite either, since combining them in this way will rarely if ever create a valid base.

**Desktop (please complete the following information):**
 - OS: Windows
 - PHP:  php 7.4
 - PHP provenance: Debian 
 - Browser Observed in Chrome and Firefox

**Plugin with the defect

 - Plugin: public forms, invitations

**Additional context**
For now my workaround is to leave the creation base in the public form at root, since this allows the system to function, however it is not ideal, considering Fusion Directory's account locks are not true account locks, anything else that attempts to authenticate directly against the LDAP server will allow the account to be used, the only way to truly prevent an account from being used before it is approved is to either make sure it has no privileges at all (by not giving it any group memberships) or by removing it from the search base other applications use to find accounts.  Either way, it undermines the usefulness of the account approval process.

**Comment by tdockx** [comment]
Hello @Window-Hero, thank you for reporting it to us. 
I'll create a ticket internally and have a look. 

We will keep you updated as soon as it has been fixed. 

Kind regards. 
Thibault

**Comment by tdockx** [comment]
Hi @Window-Hero,

Apologies for the giant delay.

We have made some tests, but I was unable to replicate your "ou" combined issue.
It is quite a complex scenario, to be honest.

This is what we have performed :
1. publicForm within its base
2. userTemplate within its base, pointing to root for user creation base.
3. invitations object within its own base pointing to another ou (base).

![image](https://github.com/fusiondirectory/fusiondirectory-plugins/assets/66223503/a82f6114-5f4e-47f8-a8c7-dfcec573bb90)


Every time, the user is created at the base referenced within the invitations objects. 
Therefore, bypassing the userTemplate base set within. 

That is true even before accepting the user (meaning the user is already present in the base set in the invitation's object).
Accepting it, should not move it to another base, I could not replicate that.

Knowing this logic, could you test again on your side with an updated version of FusionDirectory to be sure that user creation are well created, in any scenarios, within the "ou" set in the related invitation's object?

Kind regards,  
Thibault

**Comment by bilbo-the-hobbit** [comment]
no anwser closing this bug
