### ISSUE TITLE
SSH plugin: error while adding keys with space(s) in comment

### ISSUE THREAD

**Issue by matracine** [fusiondirectory/fusiondirectory-plugins#4]
Hello,

Using Debian Jessie, configured with fusiondirectory repo :
deb http://repos.fusiondirectory.org/debian-jessie jessie main
Version installed is 1.0.9.1-1.
Plugin SSH installed and fusiondirectory-plugin-ssh-schema installed/inserted on my SLAPD server.

When adding SSH public key to user, if the comment contains one or more space(s), fusiondirectory raises an error : "Unknown public key format!".

Seems to be a problem with the regexp matching key format.
Patch joined.

By the way, \s matches spaces, tabulations, cariage return, new line, vertical tabulation. This can produce bug with this regexp...
[fusiondirectory-ssh.patch.zip](https://github.com/fusiondirectory/fusiondirectory-plugins/files/65277/fusiondirectory-ssh.patch.zip)

**Comment by bilbo-the-hobbit** [comment]
hello,

i have open the issue https://forge.fusiondirectory.org/issues/4382 on our forge to look at it

Cheers

**Comment by MCMic** [comment]
Hello, 
thank you for the patch, I pushed it on our git and it will be part of 1.0.9.2 release.

Could you explain better which kind of problems the use of \s could cause? Do you think we should change it for something else? I guess the idea was to make the regexp permissive, but it might be wrong, I’m open to suggestions.

**Comment by matracine** [comment]
Bonjour,

Are you French ? I will be more fluent in french ;)
--
Matthieu Racine

**Comment by bilbo-the-hobbit** [comment]
Hello,

this as been implemented in the 1.0.9.2 version to has been released the 10 January 2016
