### ISSUE TITLE
SSH plugin: locked user can connect

### ISSUE THREAD

**Issue by matracine** [fusiondirectory/fusiondirectory-plugins#5]
Hello,

Still using Debian Jessie, configured with fusiondirectory repo :
deb http://repos.fusiondirectory.org/debian-jessie jessie main
Version installed is 1.0.9.1-1.
Plugin SSH installed and fusiondirectory-plugin-ssh-schema installed/inserted on my SLAPD server.

I use a ssh-ldap-pubkey script on my servers to connect using public key authentication.
When I lock a user in fusiondirectory, he can still connect to the server using his private key (no more sudo possible).

I think the way the user is locked is by adding a "! " to the encrypted password, so the ssh keys are not impacted...
It could be OK to do the same thing on *all* the sshPublicKey attributes of the account ?
ex : ssh-rsa !AAAAB3NzaC1yc2EAAAADAQABAAABAQD....

Or adding a keyword (diabled ?) at the begining of the key ?
ex: disabled-ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD....

Regards,

**Comment by bilbo-the-hobbit** [comment]
hello,

there is already a functionality for this its called pam_xhost_attr and can be managed with the trusted mode on the posix tab in fusionDirectory.

Cheers

**Comment by matracine** [comment]
Hello,

Do you meen pam_check_host_attr ?
I know this feature and use it for prevent or authorize users to login 
on different machines.
The feature I would be glad to use (and others users I think ;)) is to 
prevent the user to login on alls servers simply by clicking on the 
padlock in the users list.

If the user has ssh keys in his account, the padlock has no effect...

Regards,
--
Matthieu Racine

**Comment by bilbo-the-hobbit** [comment]
hello,

we use pam_authz_search to check the user and the host, but yes the padlock doesnt lock the ssh key in one rapid way, please open a wishlist bug in https://forge.fusiondirectory.org/projects/fd-plugins/issues

so we can look at it, it not sure right now :)

Cheers

**Comment by bilbo-the-hobbit** [comment]
hello,

we implemented a solution for this following https://forge.fusiondirectory.org/issues/4385 and it will be in 1.0.9.3 going out on Friday 29 January 2016
