### ISSUE TITLE
Unable to add catchall alternative mail address in mail plugin

### ISSUE THREAD

**Issue by plinss** [fusiondirectory/fusiondirectory-plugins#9]
I'm using postfix and need to set catchall email aliases. 

In the Users > Mail > Alternative adddresses I need to set values like "@example.com", however when saving I get the error: "The field 'Alternative addresses' contains invalid characters! ". It doesn't appear to accept the leading '@', however this is what postfix needs to setup a catchall address.

**Comment by bilbo-the-hobbit** [comment]
Hello,

yes we don't support catch all email adresses currently. Don't know if we will, must think about this. anyway it will be inside the postfix plugin and not inside the mail plugin for sure.

The mail plugin is the base of all other mail plugins

**Comment by plinss** [comment]
Allowing the catchall address in the mail plugin allows them to simply be additional aliases, which is all postfix needs.

I accept that there's some logic in having an additional catchall field in the postfix plugin, but it would also require additional setup at the server to support what will be plugging in as aliases anyway, as well as a schema change.

I submitted a simple PR which allows me to setup the configuration that I need. If you really feel that it should be in the postfix plugin, I can take a crack at it there instead.

**Comment by plinss** [comment]
Ok, I went ahead and added a catchall table to the postfix plugin as an alternative approach (which I think is what you were initially describing). Feel free to take either approach (or use them as a starting point for however you'd rather have it done) and close the other PR.

The table approach does require an additional alias map configured for the postfix server, and should be documented (I'll leave that for you), but there's a working example in the PR.

I also did a little fiddling with the domain value as postfix is really searching for '@domain.name' and I couldn't see how to make the LDAP search work without the '@' in the directory as part of the data, but it auto-prepends the '@' and hides it in the ui. Not sure if I got that entirely right but it seems ok on my system. Same with the schema extension to support the table.

(I also have to say I found it surprisingly easy to jump in to the code and make these changes, nicely architected system and cleanly written.)

**Comment by bilbo-the-hobbit** [comment]
hello,

opened a but in our gitlab to look at this https://gitlab.fusiondirectory.org/fusiondirectory/fd-plugins/issues/5761

Cheers

**Comment by MCMic** [comment]
@plinss Hey, if I understand correctly, allowing "@domain" as syntax for alternative address would fill the same need as the PR? Can you provide the postfix configuration which would be needed in this case?

I’m not sure which solution to use, having the catchall on the user tab seems clearer, but having things in alternativeaddresses which are not addresses could confuse a lot of tools looking at the LDAP content searching for email addresses.
Also, is that the kind of data that you’d want to give users access to (read and/or write)? (giving users access to their mail tab is easy, giving access to the cyrus service config is dangerous, this is why I ask, it would help me decide on which side this should belong)

**Comment by plinss** [comment]
Hi @MCMic, PR #10 has a quick and dirty fix that simply allows "@domain" in the alternative addresses on the mail tab. This serves the same end-goal as PR #11 but as you point out, gives regular users the ability to give themselves a catchall address. In an enterprise setting this would be undesirable (and a potential security issue) but it's simpler for small operations with trusted users as it doesn't require any additional configuration at the mail server.

In the general case, I think setting up a catchall is really more of a sysdamin task than something a regular user would do for themselves. So PR #11 is likely the better approach. There's an example postfix config in the comments of PR #11, it's used by adding it as an additional entry to the `virtual_alias_maps` setting. e.g.:

```
virtual_alias_maps = 
	ldap:/etc/postfix/ldap-virtual-alias-maps.cf,
	ldap:/etc/postfix/ldap-virtual-forward.cf,
	ldap:/etc/postfix/ldap-virtual-forward-only.cf,
	ldap:/etc/postfix/ldap-virtual-catchall.cf
```

With the file contents:
/etc/postfix/ldap-virtual-alias-maps.cf 
```
server_host = ldap.example.com
search_base = dc=example,dc=com
start_tls = yes
version = 3

bind = yes
bind_dn = uid=searchagent,ou=people,dc=example,dc=com
bind_pw = <password>

query_filter = (&(gosaMailAlternateAddress=%s)(objectClass=gosaMailAccount)(!(gosaMailDeliveryMode=[*I*])))
result_attribute = mail
```

/etc/postfix/ldap-virtual-forward.cf   
```
server_host = ldap.example.com
search_base = dc=example,dc=com
start_tls = yes
version = 3

bind = yes
bind_dn = uid=searchagent,ou=people,dc=example,dc=com
bind_pw = <password>

query_filter = (&(|(gosaMailAlternateAddress=%s)(mail=%s))(objectClass=gosaMailAccount)(!(gosaMailDeliveryMode=[*I*])))
result_attribute = mail,gosaMailForwardingAddress
```

/etc/postfix/ldap-virtual-forward-only.cf 
```
server_host = ldap.example.com
search_base = dc=example,dc=com
start_tls = yes
version = 3

bind = yes
bind_dn = uid=searchagent,ou=people,dc=example,dc=com
bind_pw = <password>

query_filter = (&(|(gosaMailAlternateAddress=%s)(mail=%s))(gosaMailDeliveryMode=[*I*])(objectClass=gosaMailAccount))
result_attribute = gosaMailForwardingAddress
```

/etc/postfix/ldap-virtual-catchall.cf 
```
server_host = ldap.example.com
search_base = dc=example,dc=com
start_tls = yes
version = 3

bind = yes
bind_dn = uid=searchagent,ou=people,dc=example,dc=com
bind_pw = <password>

query_filter = (fdCatchallTableDomain=%s)
result_attribute = fdCatchallTableRecipient
```

**Comment by bilbo-the-hobbit** [comment]
hello,

yes PR #11 is the way to go

Cheers
